### ISSUE TITLE
༼ つ ◕_◕ ༽つ 1.8.9

### ISSUE THREAD

**Issue by UndeadZeratul** [TehNut-Mods/GibMe#1]
༼ つ ◕_◕ ༽つ

**Comment by TehNut** [comment]
༼ つ ◕_◕ ༽つ

**Comment by covertusername** [comment]
༼ つ ◕_◕ ༽つ

**Comment by TehNut** [comment]
Curse isn't accepting the file for some reason. >.> After I hit `Submit file` it just refreshes the page.

**Comment by TehNut** [comment]
https://github.com/TehNut/GibMe/releases/tag/1.8.9-1.0.0-2

Best I can do until Curse lets me upload it

**Comment by Nincodedo** [comment]
:clap:
